#!/bin/bash
#
# Update 1-Wire sensors files
# Call wu-upload if needed
#
# Supposed to be run from crontab
#

HOST=$(hostname)
PREFIX='owread 28.'
WHAT='temperature'
BASE='/srv/sensors'
LOG='/var/log/sensors.log'
RRDUPDATE='rrdupdate'

declare -A S=( [kitchen]='659C55060000' [room]='978156060000' [heater]='3E3D5C060000' [ambient]='BE775C060000' [freezer]='898056060000' )

if [ -z "$1" ]; then
  echo "Usage: $0 < sensor >"
  exit 1
fi

ID=${S[$1]}

if [ -z "$ID" ]; then

  echo 'Unknown sensor!'
  exit 1

else

  CMD="$PREFIX$ID/$WHAT"
  RESULT=$($CMD 2>&1 | sed -e 's/^ *//')
  STATUS=$?
  STAMP=$(date "+%b %d %H:%M:%S")
  SSE=$(date -d "$STAMP" +%s)
  OUT="$BASE/$1"
  RRD=$BASE/$1.rrd

  if [ $STATUS == 0 -a "$RESULT" != 85 ]; then
    echo "$RESULT" >$OUT
    [ -r $RRD ] && $RRDUPDATE $RRD $SSE:$RESULT
  fi

  echo "$STAMP $1: $RESULT" >>$LOG

fi

if [ $1 == 'ambient' ]; then
  /usr/local/bin/wu-upload
fi

