#!/bin/bash

RRDTOOL='rrdtool'
CF='temperature'

cd /srv/sensors &&

DATE="$(date '+%b %d %H:%M:%S')"

FOOTER="
  -w 576 -h 240 -a PNG \
  --vertical-label Degrees \
  --font DEFAULT:7: \
  --y-grid 5:1 \
  --upper-limit 50 \
  --lower-limit -20 \
  --border 0 \
  DEF:heater=heater.rrd:$CF:LAST \
  DEF:kitchen=kitchen.rrd:$CF:LAST \
  DEF:room=room.rrd:$CF:LAST \
  DEF:ambient=ambient.rrd:$CF:LAST \
  DEF:freezer=freezer.rrd:$CF:LAST \
  LINE1:heater#FF0000:Heater \
  LINE1:kitchen#00007F:Kitchen \
  LINE1:room#0000FF:Room \
  LINE1:ambient#00FF00:Ambient \
  LINE1:freezer#00FFFF:Freezer"

$RRDTOOL graph $CF-day.png \
  --title='Temperature (daily)' \
  --start -1d --end now \
  --x-grid MINUTE:5:HOUR:1:HOUR:2:0:%H \
  --watermark "$DATE" \
  $FOOTER

$RRDTOOL graph $CF-week.png \
  --title='Temperature (weekly)' \
  --start -1w --end now \
  --x-grid HOUR:6:DAY:1:DAY:1:0:%a \
  --watermark "$DATE" \
  $FOOTER

$RRDTOOL graph $CF-month.png \
  --title='Temperature (monthly)' \
  --start -1m --end now \
  --x-grid DAY:1:WEEK:1:DAY:1:0:%d \
  --watermark "$DATE" \
  $FOOTER

$RRDTOOL graph $CF-year.png \
  --title='Temperature (yearly)' \
  --start -1y --end now \
  --x-grid WEEK:1:MONTH:1:MONTH:1:0:%b \
  --watermark "$DATE" \
  $FOOTER

