#!/bin/bash
#
# Generate PNG images using RRD as source
# Supposed to be run from crontab
#

RRDTOOL='rrdtool'
DS='temperature'
CF='LAST'
SF='-tmp'

BASE='/srv/sensors'

DATE="$(date '+%b %d %H:%M:%S')"

FOOTER="
  -w 576 -h 240 -a PNG \
  --vertical-label Degrees \
  --font DEFAULT:7: \
  --y-grid 5:1 \
  --upper-limit 50 \
  --lower-limit -20 \
  --border 0 \
  DEF:heater=$BASE/heater.rrd:$DS:$CF \
  DEF:kitchen=$BASE/kitchen.rrd:$DS:$CF \
  DEF:room=$BASE/room.rrd:$DS:$CF \
  DEF:ambient=$BASE/ambient.rrd:$DS:$CF \
  DEF:freezer=$BASE/freezer.rrd:$DS:$CF \
  LINE1:0#000000:Zero \
  LINE1:heater#FF0000:Heater \
  LINE1:kitchen#800080:Kitchen \
  LINE1:room#0000FF:Room \
  LINE1:ambient#008000:Ambient \
  LINE1:freezer#7F462C:Freezer"

$RRDTOOL graph "$BASE/$DS-day$SF.png" \
  --title='Temperature (daily)' \
  --start -1d --end now \
  --x-grid MINUTE:5:HOUR:1:HOUR:2:0:%H \
  --watermark "$DATE" \
  $FOOTER \
  VDEF:heatera=heater,AVERAGE \
  GPRINT:heatera:"%4.2lf" \

$RRDTOOL graph "$BASE/$DS-week$SF.png" \
  --title='Temperature (weekly)' \
  --start -1w --end now \
  --x-grid HOUR:6:DAY:1:DAY:1:0:%a \
  --watermark "$DATE" \
  $FOOTER

$RRDTOOL graph "$BASE/$DS-month$SF.png" \
  --title='Temperature (monthly)' \
  --start -1m --end now \
  --x-grid DAY:1:WEEK:1:DAY:1:0:%d \
  --watermark "$DATE" \
  $FOOTER

$RRDTOOL graph "$BASE/$DS-year$SF.png" \
  --title='Temperature (yearly)' \
  --start -1y --end now \
  --x-grid WEEK:1:MONTH:1:MONTH:1:0:%b \
  --watermark "$DATE" \
  $FOOTER

