#!/bin/bash
#
# Update log, RRD and remote trackers
# Depends on rrdtool and wu-upload
# Supposed to be run from crontab
#

BASE='/srv/sensors'
LOG='/var/log/sensors.log'
SENSOR='sensor'
RRDUPDATE='rrdupdate'
WUUPLOAD='wu-upload'
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

if [ -z "$1" ]; then
  echo "Usage: $0 < sensor_name >"
  exit 1
fi

RESULT=$($SENSOR $1)

if [ $? != 0 ]; then
  echo "Sensor data undefined!"
  exit 1
fi

STAMP=$(date "+%b %d %H:%M:%S")
echo "$STAMP $1: $RESULT" >>$LOG

# Update RRD
SSE=$(date -d "$STAMP" +%s)
RRD=$BASE/$1.rrd
[ -r $RRD ] && $RRDUPDATE $RRD $SSE:$RESULT

# Upload to Weather Underground
if [ $1 == 'ambient' ]; then
  echo $RESULT | $WUUPLOAD | mail -E -s "$WUUPLOAD" root
fi

