#!/bin/bash
#
# SMS informer with whitelist
# Depends on mail, sensor and smssend
# Treats all incoming SMSs beginning with $PFX as commands
#

PATH=/usr/local/sbin:/usr/local/bin:$PATH
SENSOR='sensor'
SMSSEND='smssend'
MAIL='mail'
CONFIG='/etc/sms'
WHITELIST="$CONFIG/whitelist"
ARCHIVE="/var/spool/sms/archive"
LOG='/var/log/sms/smsctl.log'
PFX="?"

[ "$1" == 'RECEIVED' ] || exit 0
[ -n "$2" ] || exit 1

FILE=$2
[ -r "$FILE" ] || exit 1
F=`basename $FILE`

log() {
  MSG=$1
  DATE="$(date '+%b %d %H:%M:%S')"
  echo "$DATE $F - $MSG" >>$LOG
}

err() {
  log "ERROR: $1"
  echo "$1" | $MAIL -s "[smsctl] $F" root
  exit 1
}

FROM=$(cat $FILE | egrep "^From: " | cut -d " " -f2)
if [ -n "$FROM" ]; then
  log "From: $FROM"
else
  err 'Empty From: header!'
fi

ALLOW=0
for PHONE in $(cat $WHITELIST); do
  cat $FILE | grep "From: $PHONE" >/dev/null 2>&1
  [ $? -eq 0 ] && ALLOW=1
done;
[ $ALLOW -eq 0 ] && err "Access denied! ($FROM)"

CMD=$(cat $FILE | egrep "^\\$PFX" | cut -d "$PFX" -f2)
if [ -n "$CMD" ]; then
  log "CMD: $CMD"
else
  err 'CMD not found!'
fi

OUT=''
case "$CMD" in

  'temp')
    for S in cpu freezer ambient heater room kitchen ; do
      O=$($SENSOR $S)
      [ -n $O ] && OUT="$S=$O $OUT"
    done
    log "Out: $OUT"
    ;;

  'wake')
    OUT=$(wake)
    ;;

  '*')
    OUT='Unknown command!'
    ;;

esac

if [ -n "$O" ]; then
  $SMSSEND $FROM "$OUT"
  if [ $? -eq 0 ]; then
    log "To: $FROM"
  else
    err "Sending failed!"
  fi
  mv $FILE $ARCHIVE && log "Archived"
fi

exit 0

